FROM node:18-alpine As development

WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy source code
COPY . .

# Run in development mode with debug enabled
CMD ["npm", "run", "start:debug"]