FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install -g @nestjs/cli && npm install

COPY . .

# Проверяем наличие директории перед созданием
RUN if [ ! -d "/app/uploads" ]; then mkdir -p /app/uploads && chmod 777 /app/uploads; fi

# Используем команду для запуска в режиме разработки
CMD ["npm", "run", "start:debug"]