FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install -g @nestjs/cli && npm install

COPY . .

# Создаем директорию для загрузки файлов и устанавливаем права
RUN mkdir -p /app/uploads && chmod 777 /app/uploads

# Используем команду по умолчанию для запуска в режиме разработки
# В docker-compose.yml есть своя команда, которая переопределит эту
CMD ["npm", "run", "start:dev"]