FROM node:18-alpine AS development

WORKDIR /app

COPY package*.json ./

# Добавляем глобальную установку NestJS CLI
RUN npm install -g @nestjs/cli && npm install

COPY . .

RUN npm run build

FROM node:18-alpine AS production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /app

COPY package*.json ./

# Изменяем на установку всех зависимостей, включая devDependencies для типов
RUN npm install

# Копируем исходники
COPY . .

# Копируем собранное приложение из development стадии
COPY --from=development /app/dist ./dist

# Меняем команду запуска на прямой вызов node
CMD ["node", "dist/main"]